import eslint from "@eslint/js";
import { fixupPluginRules } from "@eslint/compat";
import globals from "globals";
import tseslint from "typescript-eslint";
import * as deprecation from "eslint-plugin-deprecation";

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  // ...tseslint.configs.stylisticTypeChecked,
  {
    files: ["src/**/*.js"],
    ignores: ["node_modules/**/*.*", "types/**/*.d.ts"],
    plugins: { deprecation: fixupPluginRules(deprecation) },
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "module",
      globals: { ...globals.browser, ...globals.es2021 },
      parser: tseslint.parser,
      parserOptions: { tsconfigRootDir: ".", project: "./tsconfig.json" },
    },
    rules: {
      "accessor-pairs": "error",
      "array-bracket-newline": "off",
      "array-bracket-spacing": ["error", "never"],
      "array-callback-return": "error",
      "array-element-newline": "off",
      "arrow-body-style": "warn",
      "arrow-parens": ["error", "always"],
      "arrow-spacing": ["error", { after: true, before: true }],
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-floating-promises": "off",
      "block-scoped-var": "error",
      "block-spacing": "error",
      "brace-style": ["error", "1tbs"],
      camelcase: "warn",
      "capitalized-comments": "warn",
      "class-methods-use-this": "error",
      "comma-dangle": "off",
      "comma-spacing": ["error", { after: true, before: false }],
      "comma-style": ["error", "last"],
      complexity: "warn",
      "computed-property-spacing": ["error", "never"],
      "consistent-return": "warn",
      "consistent-this": "error",
      curly: "off",
      "default-case": "off",
      "default-case-last": "error",
      "default-param-last": "error",
      "deprecation/deprecation": "warn",
      "dot-location": ["error", "property"],
      "dot-notation": ["error", { allowKeywords: true }],
      "eol-last": "error",
      eqeqeq: "warn",
      "func-call-spacing": "error",
      "func-name-matching": "error",
      "func-names": "off",
      "func-style": "off",
      "function-call-argument-newline": ["error", "consistent"],
      "function-paren-newline": "off",
      "generator-star-spacing": "error",
      "grouped-accessor-pairs": "error",
      "guard-for-in": "error",
      "id-denylist": "error",
      "id-length": "off",
      "id-match": "error",
      "implicit-arrow-linebreak": "off",
      indent: "off",
      "init-declarations": "off",
      "jsx-quotes": "error",
      "key-spacing": "error",
      "keyword-spacing": ["error", { after: true, before: true }],
      "line-comment-position": "off",
      "linebreak-style": ["error", "unix"],
      "lines-around-comment": "off",
      "lines-between-class-members": "error",
      "max-classes-per-file": "error",
      "max-depth": "off",
      "max-len": "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "max-nested-callbacks": "error",
      "max-params": "off",
      "max-statements": "off",
      "max-statements-per-line": "error",
      "multiline-comment-style": "off",
      "multiline-ternary": ["error", "always-multiline"],
      "new-parens": "error",
      "newline-per-chained-call": "error",
      "no-alert": "off",
      "no-array-constructor": "error",
      "no-await-in-loop": "warn",
      "no-bitwise": ["error", { int32Hint: true }],
      "no-caller": "error",
      "no-confusing-arrow": "off",
      "no-console": "off",
      "no-constructor-return": "error",
      "no-continue": "off",
      "no-div-regex": "error",
      "no-duplicate-imports": "error",
      "no-else-return": "warn",
      "no-empty-function": "error",
      "no-eq-null": "warn",
      "no-eval": "off",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-extra-parens": "off",
      "no-floating-decimal": "error",
      "no-implicit-globals": "off",
      "no-implied-eval": "error",
      "no-inline-comments": "off",
      "no-invalid-this": ["error", { capIsConstructor: true }],
      "no-iterator": "error",
      "no-label-var": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-loop-func": "warn",
      "no-magic-numbers": "off",
      "no-mixed-operators": "off",
      "no-multi-assign": "error",
      "no-multi-spaces": "error",
      "no-multi-str": "error",
      "no-multiple-empty-lines": "error",
      "no-negated-condition": "off",
      "no-nested-ternary": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-object": "error",
      "no-new-wrappers": "error",
      "no-octal-escape": "error",
      "no-param-reassign": "off",
      "no-plusplus": "off",
      "no-promise-executor-return": "warn",
      "no-proto": "error",
      "no-restricted-exports": "error",
      "no-restricted-globals": "error",
      "no-restricted-imports": "error",
      "no-restricted-properties": "error",
      "no-restricted-syntax": "error",
      "no-return-assign": "error",
      "no-return-await": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-shadow": "error",
      "no-tabs": "off",
      "no-template-curly-in-string": "error",
      "no-ternary": "off",
      "no-throw-literal": "error",
      "no-trailing-spaces": "error",
      "no-undef-init": "warn",
      "no-undefined": "warn",
      "no-undef": "off",
      "no-underscore-dangle": "warn",
      "no-unmodified-loop-condition": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable-loop": "error",
      "no-unused-expressions": "error",
      "no-unused-private-class-members": "error",
      "no-use-before-define": "off",
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-var": "warn",
      "no-void": "error",
      "no-warning-comments": "warn",
      "no-whitespace-before-property": "error",
      "nonblock-statement-body-position": ["error", "any"],
      "object-curly-newline": "error",
      "object-curly-spacing": ["error", "always"],
      "object-shorthand": "warn",
      "one-var": "off",
      "one-var-declaration-per-line": "error",
      "operator-assignment": "warn",
      "operator-linebreak": ["error", null],
      "padded-blocks": "off",
      "padding-line-between-statements": "error",
      "prefer-arrow-callback": "warn",
      "prefer-const": "warn",
      "prefer-destructuring": "warn",
      "prefer-exponentiation-operator": "error",
      "prefer-named-capture-group": "off",
      "prefer-numeric-literals": "error",
      "prefer-object-has-own": "off",
      "prefer-object-spread": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-regex-literals": "error",
      "prefer-rest-params": "off",
      "prefer-spread": "error",
      "prefer-template": "warn",
      "quote-props": "off",
      quotes: "off",
      radix: ["error", "as-needed"],
      "require-atomic-updates": "error",
      "require-await": "off",
      "require-unicode-regexp": "off",
      "rest-spread-spacing": ["error", "never"],
      semi: "error",
      "semi-spacing": ["error", { after: true, before: false }],
      "semi-style": ["error", "last"],
      "sort-imports": "off",
      "sort-keys": "off",
      "sort-vars": "error",
      "space-before-blocks": "error",
      "space-before-function-paren": "off",
      "space-in-parens": ["error", "never"],
      "space-infix-ops": "error",
      "space-unary-ops": "error",
      "spaced-comment": "warn",
      strict: "off",
      "switch-colon-spacing": "error",
      "symbol-description": "error",
      "template-curly-spacing": ["error", "never"],
      "template-tag-spacing": "error",
      "unicode-bom": ["error", "never"],
      "vars-on-top": "error",
      "wrap-regex": "off",
      "yield-star-spacing": "error",
      yoda: ["error", "never"],
    },
  }
);
