import eslint from "@eslint/js";
import { defineConfig } from 'eslint/config';
import stylistic from '@stylistic/eslint-plugin'
import tseslint from "typescript-eslint";
import globals from "globals";

export default defineConfig(
  eslint.configs.recommended,
  stylistic.configs.customize({ quotes: "double", semi: true, jsx: false, braceStyle: "1tbs" }),
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    files: ["src/**/*.{j,t}s"],
    ignores: ["node_modules/**/*.*", "types/**/*.d.ts"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser },
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      "@stylistic/quote-props": ["error", "as-needed"],
      "@stylistic/comma-dangle": ["error", { arrays: "always-multiline", objects: "always-multiline", imports: "always-multiline" }],
      "@stylistic/quotes": ["error", "double", { "avoidEscape": true }],
      "@stylistic/operator-linebreak": ["error", "after"],
      "@stylistic/space-before-function-paren": ["error", "never"],
      "@stylistic/array-bracket-newline": ["error", { "multiline": true }],
      "@stylistic/array-element-newline": ["error", "consistent"],
      "@stylistic/function-call-argument-newline": ["error", "consistent"],
      "@stylistic/function-call-spacing": ["error", "never"],
      "@stylistic/linebreak-style": ["error", "unix"],
      "@stylistic/no-extra-semi": "error",
      "@stylistic/nonblock-statement-body-position": ["error", "beside"],
      "@stylistic/object-curly-newline": ["error", {
        "ObjectExpression": { "multiline": true },
        "ObjectPattern": { "multiline": true },
        "ImportDeclaration": { "multiline": true },
        "ExportDeclaration": { "multiline": true },
        "TSTypeLiteral": { "multiline": true },
        "TSInterfaceBody": { "consistent": true }
      }],
      "@stylistic/one-var-declaration-per-line": ["error", "initializations"],
      "@stylistic/semi-style": ["error", "last"],
      "@stylistic/switch-colon-spacing": "error",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-floating-promises": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/no-confusing-void-expression": "off", // enable that too
      "@typescript-eslint/restrict-template-expressions": ["error", { allowAny: true }],
      "@typescript-eslint/no-unnecessary-condition": "off",
      "@typescript-eslint/no-dynamic-delete": "off",
      "@typescript-eslint/no-deprecated": "warn",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "off",
      "@typescript-eslint/no-unnecessary-type-parameters": "off",
      "accessor-pairs": "error",
      "array-callback-return": "error",
      "arrow-body-style": "warn",
      "block-scoped-var": "error",
      "capitalized-comments": "off",
      "class-methods-use-this": "error",
      "consistent-return": "warn",
      "consistent-this": "error",
      "default-case-last": "error",
      "default-param-last": "error",
      "dot-notation": ["error", { allowKeywords: true }],
      eqeqeq: ["warn", "smart"],
      "func-name-matching": "error",
      "func-names": ["warn", "as-needed"],
      "func-style": ["error", "declaration"],
      "grouped-accessor-pairs": "error",
      "guard-for-in": "error",
      "id-denylist": "error",
      "id-match": "error",
      "max-classes-per-file": "error",
      "max-nested-callbacks": "error",
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-await-in-loop": "warn",
      "no-bitwise": ["error", { int32Hint: true }],
      "no-caller": "error",
      "no-constructor-return": "error",
      "no-div-regex": "error",
      "no-duplicate-imports": "error",
      "no-else-return": "warn",
      "no-empty-function": "error",
      "no-eq-null": "warn",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-invalid-this": ["error", { capIsConstructor: true }],
      "no-iterator": "error",
      "no-label-var": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-multi-assign": "error",
      "no-multi-str": "error",
      "no-nested-ternary": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-octal-escape": "error",
      "no-promise-executor-return": "warn",
      "no-proto": "error",
      "no-restricted-exports": "error",
      "no-restricted-globals": "error",
      "no-restricted-imports": "error",
      "no-restricted-properties": "error",
      "no-restricted-syntax": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-shadow": "error",
      "no-template-curly-in-string": "error",
      "no-throw-literal": "error",
      "no-undef-init": "warn",
      "no-undefined": "warn",
      "no-undef": "off",
      "no-unmodified-loop-condition": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable-loop": "error",
      "no-unused-expressions": "error",
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-var": "warn",
      "no-void": "error",
      "no-warning-comments": "warn",
      "object-shorthand": "warn",
      "operator-assignment": "warn",
      "prefer-arrow-callback": "warn",
      "prefer-const": ["warn", { "destructuring": "all" }],
      "prefer-destructuring": "warn",
      "prefer-exponentiation-operator": "error",
      "prefer-numeric-literals": "error",
      "prefer-object-has-own": "error",
      "prefer-object-spread": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-regex-literals": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "warn",
      radix: ["error", "as-needed"],
      "require-atomic-updates": "error",
      "require-await": "error",
      "sort-vars": "error",
      strict: "error",
      "symbol-description": "error",
      "unicode-bom": ["error", "never"],
      "vars-on-top": "error",
      yoda: ["error", "never"],
    },
  }
);
